version: "3"
services:
  web:
    image: waramity-portfolio
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./wsgi.py
    ports:
      - "5000:5000"
    volumes:
      - "./app:/app"
