version: "3"
services:
  web:
    # image: waramity-portfolio
    build:
      context: .
      dockerfile: Dockerfile
        #    entrypoint:
        #      - python 
        #      - wsgi.py
        #      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: "1"
          #environment:
          #j - FLASK_ENV=development
    ports:
      - "5001:5001"
    volumes:
      - "./app:/app"
